language: python

os: linux

jobs:
  include:
    - python: 3.6
      arch: arm64
    - python: 3.7
      arch: arm64
    - python: 3.8
      arch: arm64
      
 install:
   - sudo apt-get update
   - sudo apt-get -y install dictionaries-common aspell aspell-en hunspell-en-us libenchant1c2a enchant     
    
 script:
   - ./scripts/manylinux/build.sh
   - ./scripts/manylinux/check.sh
